### ISSUE TITLE
Explain what is a migration in the documentation

### ISSUE THREAD

**Issue by max-l** [trufflesuite/trufflesuite.github.io#11]
Ethereum newbe here, Truffle seems like a good intruduction to ethereum, I have many guesses what migrations can be, it would be nice if the doc would explain what purpose they serve.

  http://truffleframework.com/docs/getting_started/migrations

**Comment by bmmpxf** [comment]
Hi @max-l . We've updated that page and believe that we've put a rudimentary introduction to migrations there. If you think there is important information that we missed, please let us know!
