### ISSUE TITLE
Update doc for NPM packages to use `zeppelin-solidity`

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/trufflesuite.github.io#119]
Currently http://truffleframework.com/docs/getting_started/packages-npm is out of date.

This section should be replaced to show usage of OpenZeppelin as a library.

**Comment by bmmpxf** [comment]
Hey @gnidan , do we still need this? I can certainly add a section on OpenZeppelin if need be, but we do have a [tutorial](http://truffleframework.com/tutorials/robust-smart-contracts-with-openzeppelin) about it now. Feel free to reopen though and I'll take a look.
