### ISSUE TITLE
Minor issues with end of tutorial

### ISSUE THREAD

**Issue by jrodenbostel** [trufflesuite/trufflesuite.github.io#131]
Current version of MetaMask and TestRPC don't have button labels that match current version of MetaMask(3.9.1) for Chrome (59.0.3071.115) on MacOS (10.12.5).  Instead of clicking on the "Adopt" button and getting prompted to "Approve" in  MetaMask as the tutorial describes, I get prompted to "Submit", which then results in MetaMask hanging and either the request never being accepted or failing with the error seen in the screen shot below.  Doesn't seem to be a truffle problem, but an issue with the tutorial itself.
<img width="201" alt="screen shot 2017-07-21 at 5 33 25 pm" src="https://user-images.githubusercontent.com/283503/28524178-033bbcd4-7045-11e7-8ba0-a3b526655b7b.png">
.

**Comment by DiscRiskandBisque** [comment]
@jrodenbostel Updated the screenshots--thanks for pointing that out!

Regarding the hanging: Other users, including myself, have experience this issue with MetaMask as well. It's being tracked by the MM team [here](https://github.com/MetaMask/metamask-extension/issues/1654).
