### ISSUE TITLE
Fix homepage links to point to truffleframework.com/docs

### ISSUE THREAD

**Issue by gnidan** [trufflesuite/trufflesuite.github.io#135]
<img width="968" alt="screen shot 2017-07-26 at 4 56 09 pm" src="https://user-images.githubusercontent.com/151065/28643289-5e9f5ea2-7223-11e7-8885-b5ebebcedb6d.png">

**Comment by bmmpxf** [comment]
These should all be updated. If you find any bad links, please let me know!
