### ISSUE TITLE
Syndicate these VS blog posts as tutorials

### ISSUE THREAD

**Issue by tcoulter** [trufflesuite/trufflesuite.github.io#16]
* https://davidburela.wordpress.com/2016/11/18/how-to-install-truffle-testrpc-on-windows-for-blockchain-development/
* https://davidburela.wordpress.com/2016/12/23/ethereum-devops-with-truffle-testrpc-visual-studio-team-services/
* https://davidburela.wordpress.com/2016/11/18/configuring-visual-studio-code-for-ethereum-blockchain-development/

David Burela has graciously given us permission to syndicate these on our site and link back to the original. We want to make sure we list him as the author.

**Comment by DavidBurela** [comment]
Closed!
http://truffleframework.com/#tutorials

**Comment by tcoulter** [comment]
Whoops. Thanks!
