### ISSUE TITLE
Pet shop tutorial deploy error

### ISSUE THREAD

**Issue by si-harps** [trufflesuite/trufflesuite.github.io#177]
Hi, thanks for the great pet-shop tutorial. When i first run the DAPP on Chrome using metamask i received a deployment error in the console when clicking the "Adopt" button on each of the pets.

In order to run the application successfully i had to exec `truffle deploy` but this wasn't documented in the tutorial itself.

Is this expected behaviour?

**Comment by bmmpxf** [comment]
Hi there @si-harps . We've rewritten this tutorial to be compatible with Truffle 4, and that issue should not be there now.

Closing this, but if you still find an error, please feel free to raise it on our new website source repo: https://github.com/trufflesuite/trufflesuite.com. Thanks!
