### ISSUE TITLE
Update "Using Infura" tutorial to use "truffle-hdwallet-provider"

### ISSUE THREAD

**Issue by pabloruiz55** [trufflesuite/trufflesuite.github.io#207]
The "Using Infura" tutorial could be extremely short and simple to implement if it used the truffle-hdwallet-provider npm package.
Just 2 lines of code to set it up instead of 15+ which require several additional includes.

I'd like to modify this page/tutorial to make it easier to deploy to Infura.

**Comment by bmmpxf** [comment]
Hi @pabloruiz55 . This has been done. Check it out: http://truffleframework.com/tutorials/using-infura-custom-provider

Feel free to open up more issues over at https://github.com/trufflesuite/trufflesuite.com/issues, and we'll get to them much faster, we promise! Thanks!
