### ISSUE TITLE
explain what `frontend` file you refer to

### ISSUE THREAD

**Issue by SCBuergel** [trufflesuite/trufflesuite.github.io#21]
You [mention]:(https://github.com/trufflesuite/truffleframework.github.io/blob/master/docs/getting_started/contracts.html#L243)
>look at the Javascript object called <code>MetaCoin</code> provided for us by Truffle and Ether Pudding, made available within our frontend:

It should be noted which file this refers to. This certainly is not in the Solidity file that you discuss in the previous paragraph (which BTW should also be clearly mentioned where in the default folder structure this file is found).

**Comment by bmmpxf** [comment]
Hi @SCBuergel . Very late to the party here, but this has been addressed:

http://truffleframework.com/docs/getting_started/contracts

If you see any other issues in our documentation, please register them over at https://github.com/trufflesuite/trufflesuite.com/issues and we'll get to them much quicker, we promise. Thanks!
