### ISSUE TITLE
In pet shop tutorial, pet with id 11 is a "Scottish Terrier", not a "Golden Retriever"

### ISSUE THREAD

**Issue by friedger** [trufflesuite/trufflesuite.github.io#215]
pets.json in the zip file needs to be updated

**Comment by bmmpxf** [comment]
Right you are! Fixed with https://github.com/truffle-box/pet-shop-box/commit/dbfe2b91bfdac8ef2645ff7a8ca6ed1ffd7dcb41

Thanks for keeping our pet shop honest @friedger. 😄
