### ISSUE TITLE
no target for "See a way to make this page better? Edit here" links

### ISSUE THREAD

**Issue by p-alik** [trufflesuite/trufflesuite.github.io#219]
I faced the issue on the following tutorial pages:

- (OpenZeppelin)[https://github.com/trufflesuite/trufflesuite.github.io/blob/master/tutorials/robust-smart-contracts-with-openzeppelin.html#L326]
- (Pet Shop)[https://github.com/trufflesuite/trufflesuite.github.io/blob/master/tutorials/pet-shop.html#L665]
- (Debugging a smart contract)[https://github.com/trufflesuite/trufflesuite.github.io/blob/master/tutorials/debugging-a-smart-contract.html#L618]

**Comment by bmmpxf** [comment]
Hi @p-alik . You're totally correct. We recently separated out the source of the website from the built objects to make it easier for people to know what to change. The new website source is at http://github.com/trufflesuite/trufflesuite.com .

However, we neglected to update the footer of the pages to point to the new repository. Apologies. This should be fixed now as of https://github.com/trufflesuite/trufflesuite.com/commit/7feaf46a5437cc085c1460ea338c9be67703bff9
 
Thanks for finding that. Please feel free now to go ahead and make edits!
