### ISSUE TITLE
Update Docs to Ganache instead of TestRPC

### ISSUE THREAD

**Issue by heartz** [trufflesuite/trufflesuite.github.io#221]
There's quite a few places on the Docs where it still says TestRPC, would be nice to update them to Ganache-cli

**Comment by bmmpxf** [comment]
Hi @heartz . Agreed! That is a work in progress, but we're on it. Feel free to submit PRs too if you'd like to see it updated faster. Thanks!

**Comment by bmmpxf** [comment]
Okay, all mentions of the TestRPC in the docs should be replaced by Ganache now, except where the distinction is important.

See:
* https://github.com/trufflesuite/trufflesuite.com/pull/37
* https://github.com/trufflesuite/trufflesuite.com/pull/15

We haven't tackled all of the [tutorials](http://truffleframework.com/tutorials/) yet, but we'll be going through them shortly. If you see anything else that needs updating, please let us know on our new website issue tracker: https://github.com/trufflesuite/trufflesuite.com/issues . Thanks!
