### ISSUE TITLE
Update all URLs to HTTPS

### ISSUE THREAD

**Issue by himanshub16** [trufflesuite/trufflesuite.github.io#223]
Currently, the links in `README` and multiple places on landing page use `http`, which
1. Violates privacy
2. Get blocked in browsers having extensions like `https_everywhere` or recent versions of Chrome.

**Comment by bmmpxf** [comment]
Hi @himanshub16 . Thanks for raising this issue. HTTPS is important to us too.

I've edited the README for this repository to show HTTPS links. Unfortunately, we can't do anything about the truffleframework.com site at the moment. But I have raised an issue on our main website repository for this.

https://github.com/trufflesuite/trufflesuite.com/issues/97

In the meantime, if you see any specific links that could be HTTPS but aren't, please submit an issue on our website repo: https://github.com/trufflesuite/trufflesuite.com . (We're trying to move away from having issues and PRs on this repo.) Thanks!
