### ISSUE TITLE
Images not displaying after running npm run dev?

### ISSUE THREAD

**Issue by mudkipium** [trufflesuite/trufflesuite.github.io#224]
I feel like this is a bit of a broad question, but I'm stuck on the last step of the pet shop tutorial. It seems that I've copied the code from the tutorial 100% but the images aren't loading when I check localhost:3000. Is anyone else having this issue?

My repo for this is here: https://github.com/mudkipium/pet-shop-tutorial

The tests run fine and MetaMask seems to be configured properly (I can see the ETH in the account and it matches what shows in Ganache), so I'm assuming it's somewhere in app.js (since it's just the front-end part that isn't working out). Any ideas?

Thank you!

**Comment by mudkipium** [comment]
Just kidding, I fixed it! It's my first time writing JS so it was something silly >.< Thanks anyway!

**Comment by vgangodi** [comment]
@mudkipium hi, I struck at the same issue. can you please advice me on this. how can I fix this issue. I really appreciate it.
Thank you.

**Comment by mudkipium** [comment]
I fixed it in this commit :) https://github.com/mudkipium/pet-shop-tutorial/commit/fa9d6c81a94a8e11ff0b5bda4e8cc7fc93e6b368

**Comment by vgangodi** [comment]
@mudkipium Hi, Thank you for your reply. I checked my app.js file and cross referenced with the link that you mentioned above, everything looks same,  still I'm getting blank display. I couldn't find where I did mistake, can you help with this. here is the code https://github.com/vgangodi/Blockchain/tree/master/petshop

Thank you very much.
