### ISSUE TITLE
explain relationship to web3 in documentation

### ISSUE THREAD

**Issue by SCBuergel** [trufflesuite/trufflesuite.github.io#72]
Truffle is using a ton of background magic that is challenging new users. Most of them are very well explained and references provided (e.g. for testing via mocha and chai). In your examples you are calling e.g. [`instance.getBalance.call(accounts[0]);`](http://truffleframework.com/docs/getting_started/javascript-tests#example). For the novice user it is not clear what is going on here and how this happens to be. I assume that you are relying on web3.js or at least have a similar functionality to the one described [in their docs](instance.getBalance.call(accounts[0]);), which I'd link along with a short explainer that this wraps a smart contract with JS functionality and some magic connection between the two that allows javascript to directly write/read to/from storage on the blockchain.

**Comment by tcoulter** [comment]
Hi there. Have you seen this page in our documentation? http://truffleframework.com/docs/getting_started/contracts

It explains transactions and calls, the difference, and what that means for users. Let us know if A) this page has the information you were expecting, and B) it's prominently displayed enough for new users. 

We have other content in the works to better explain contract development for new users. Stay tuned - that content should be released next week!

I'm going to close this ticket for now. Please comment and reopen if this doesn't answer your question. Thanks!
