### ISSUE TITLE
Add parity to the list of clients

### ISSUE THREAD

**Issue by rstormsf** [trufflesuite/trufflesuite.github.io#81]
http://truffleframework.com/docs/getting_started/client - this URL doesn't specify that Parity could also be used for ethereum Dapp development.

**Comment by igorbarinov** [comment]
@rstormsf  you can fork, edit and propose pull request https://github.com/trufflesuite/trufflesuite.github.io/edit/master/_site/public/docs/getting_started/client.md

If it is politically correct, it will be accepted. Therefore, I'm not sure it will be added.
